# Generated by Django 5.2.6 on 2025-11-02 15:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0002_alter_profile_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'حساب کاربری', 'verbose_name_plural': 'حساب ها'},
        ),
        migrations.AlterField(
            model_name='profile',
            name='father_s_name',
            field=models.CharField(max_length=30, verbose_name='نام پدر'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/image', verbose_name='عکس'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='melicode',
            field=models.IntegerField(max_length=20, verbose_name='کد ملی'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
    ]
