# Generated by Django 5.2.6 on 2025-09-25 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0002_alter_articlemodel_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlemodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/blogs'),
        ),
    ]
