# Generated by Django 5.2.6 on 2025-09-28 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0004_articlemodel_author_alter_articlemodel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlemodel',
            name='body',
            field=models.TextField(help_text='Enter a valid body because important!'),
        ),
    ]
