# Generated by Django 5.2.6 on 2025-09-29 19:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0006_alter_articlemodel_author_alter_articlemodel_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlemodel',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2025, 9, 29, 19, 33, 47, 677017, tzinfo=datetime.timezone.utc)),
        ),
    ]
