# Generated by Django 5.2.6 on 2025-09-29 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0007_articlemodel_pub_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='articlemodel',
            name='pub_date',
        ),
        migrations.AddField(
            model_name='articlemodel',
            name='category',
            field=models.ManyToManyField(related_name='article_category', to='blog_app.category'),
        ),
    ]
