# Generated by Django 5.2.6 on 2025-09-29 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0008_category_remove_articlemodel_pub_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlemodel',
            name='title',
            field=models.CharField(max_length=40),
        ),
    ]
