# Generated by Django 5.2.6 on 2025-10-04 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0009_alter_articlemodel_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlemodel',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True),
        ),
    ]
