# Generated by Django 5.2.6 on 2025-10-15 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0015_comment_parent_id_delete_reply_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='parent_id',
            new_name='parent',
        ),
    ]
